import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

type GuideItem={id:string;en:[string,string,string];zh:[string,string,string];image:string;altEn:string;altZh:string};
const sections:GuideItem[]=[
  {id:"construction",en:["Basic construction","A silicone keypad typically combines a key surface, web or return geometry, conductive area and mounting relationship. The original diagram is a reference for discussing parts—not a universal section for every design.","Share the intended key layout, available height, mounting surface and any existing section drawing."],zh:["基本结构与部件","硅胶按键通常需要同时讨论按键面、回弹结构、导电区域与安装关系。原图用于理解部件，不代表所有设计都采用同一截面。","准备按键布局、可用高度、安装面及已有截面图。"],image:"/assets/guide-construction.webp",altEn:"Reference illustration of silicone keypad basic construction",altZh:"硅胶按键基本结构参考图"},
  {id:"conductive-design",en:["Conductive design","The public reference shows several conductive-contact patterns. Contact geometry, resistance targets and circuit interface need to be confirmed against the actual electronics and mechanical stack-up.","Share the PCB contact layout, switching requirement and any target resistance or test method that must be reviewed."],zh:["导电触点与设计形式","公开参考图展示多种导电触点形式。触点几何、阻值目标与电路接口需结合实际电子与机械叠层确认。","准备 PCB 触点布局、开关需求，以及需要评估的目标阻值或测试方法。"],image:"/assets/guide-conductive.webp",altEn:"Reference patterns for conductive keypad design",altZh:"按键导电设计形式参考图"},
  {id:"special-design",en:["Special design reference","Special constructions may address key shape, light behavior, sealing or assembly constraints. The source illustration is useful for identifying a discussion topic, not for assuming a validated solution.","Mark the constraint on a sketch and explain what the feature must do in the final assembly."],zh:["特殊设计参考","特殊结构可能涉及按键形状、灯光表现、密封或装配限制。原图用于识别讨论主题，不代表方案已经验证。","在草图上标出限制，并说明该结构在最终装配中的用途。"],image:"/assets/guide-special-design.webp",altEn:"Special silicone keypad construction reference",altZh:"硅胶按键特殊结构参考图"},
  {id:"assembly",en:["Assembly considerations","Keypad behavior depends on the surrounding housing, PCB support, compression and alignment. The assembly reference helps identify interfaces that need dimensions and tolerances.","Provide the housing, PCB and keypad relationship, including fasteners, support points and available compression."],zh:["装配需要讨论的问题","按键表现会受到外壳、PCB 支撑、压合与定位影响。装配参考图帮助识别需要尺寸与公差的接口。","提供外壳、PCB 与按键的关系，包括紧固方式、支撑点及可用压合空间。"],image:"/assets/guide-assembly.webp",altEn:"Silicone keypad assembly design reference",altZh:"硅胶按键装配设计参考图"},
  {id:"color-and-marking",en:["Color & marking","Base color and visible legends need separate definition. Printing, engraving and other marking methods have different artwork and process implications.","List base colors, legend colors, viewing conditions and any critical alignment or identification requirement."],zh:["颜色、字符、雕刻与印刷","基体颜色与可见字符需分别定义。印刷、雕刻等标识方式对应不同图稿与工艺条件。","列出基体颜色、字符颜色、观看条件，以及关键对位或识别要求。"],image:"/assets/guide-color-printing.webp",altEn:"Color and printing reference for silicone keys",altZh:"硅胶按键颜色与印刷参考图"},
  {id:"surface-finishes",en:["Surface finishes","Public samples show several finish approaches, including epoxy-style coatings. The correct finish depends on appearance, feel, legend protection and use conditions.","Describe the desired appearance, touch and what the finish is expected to protect; performance needs project testing."],zh:["表面处理参考","公开样本展示滴胶等多种表面处理思路。合适工艺取决于外观、触感、字符保护和使用条件。","说明预期外观、触感及希望保护的内容；性能需按项目测试。"],image:"/assets/guide-epoxy.webp",altEn:"Epoxy coating reference for a silicone key",altZh:"硅胶按键滴胶处理参考图"},
  {id:"artwork",en:["Artwork preparation","Artwork should define legend content, location, orientation and print relationship. Small features and curved surfaces may need process review before final artwork release.","Provide editable artwork where possible and identify critical size, alignment and color references."],zh:["图稿与印刷准备","图稿应说明字符内容、位置、方向与印刷关系。小尺寸特征和曲面可能需要在正式放图前做工艺评估。","尽量提供可编辑图稿，并标注关键尺寸、对位和颜色参考。"],image:"/assets/guide-color-printing.webp",altEn:"Reference diagram for keypad legend and printing artwork",altZh:"按键字符与印刷图稿参考图"},
  {id:"special-construction",en:["Special construction","Insert features, light paths and non-standard key sections can create dependencies across tooling, molding and assembly. Treat the original image as a prompt for review.","Explain the purpose of the special feature and share the neighboring parts it must fit or interact with."],zh:["特殊结构示意","嵌件、导光或非标准截面会同时影响模具、成型与装配。原图只作为评审提示。","说明特殊结构的目的，并提供相邻配合或互动零件资料。"],image:"/assets/guide-special-design.webp",altEn:"Reference illustration of special silicone keypad construction",altZh:"硅胶按键特殊结构示意图"},
  {id:"life-test",en:["Life-test reference","A life-test diagram explains how repeated actuation may be evaluated. Values shown in a reference image are not a blanket durability guarantee for every keypad.","State the expected duty cycle, actuation method, environment and any acceptance criteria that require agreement."],zh:["寿命测试参考","寿命测试图说明可能如何进行重复按压评估。参考图中的数值不构成所有按键的统一耐久保证。","说明预期工作循环、按压方式、环境与需确认的验收标准。"],image:"/assets/guide-life-test.webp",altEn:"Reference illustration for silicone keypad life testing",altZh:"硅胶按键寿命测试参考图"},
  {id:"force-stroke",en:["Reading force & stroke","Force/stroke curves help describe tactile response across travel. The exact curve depends on geometry, material, measurement setup and the surrounding assembly.","Share the preferred feel, target travel if known, comparison sample and the measurement condition you need to match."],zh:["力与行程曲线","力与行程曲线用于描述按压过程中的触感响应。实际曲线取决于结构、材料、测量方式与周边装配。","准备触感偏好、已知行程目标、对比样品及需要匹配的测量条件。"],image:"/assets/guide-force-stroke.webp",altEn:"Reference force and stroke curve for silicone rubber keys",altZh:"硅胶按键力与行程曲线参考图"},
  {id:"tolerance",en:["Tolerance reference","Tolerance needs to be discussed by feature and function. A general table can start the conversation, but critical dimensions require drawing-level agreement and measurement definition.","Identify critical-to-function dimensions, datums, fit relationships and how each dimension will be inspected."],zh:["公差参考","公差应按特征与功能讨论。通用表格可以作为起点，但关键尺寸仍需在图纸层面确认测量定义。","标出关键功能尺寸、基准、配合关系以及每个尺寸的检验方式。"],image:"/assets/guide-assembly.webp",altEn:"Assembly reference used to discuss critical dimensions and tolerances",altZh:"用于讨论关键尺寸与公差的装配参考图"},
  {id:"key-sections",en:["Key sections","Different key sections change appearance, travel, support and molding considerations. The reference sheet helps compare shapes before a project-specific section is developed.","Provide the preferred top profile, key spacing, wall relationship and any height or travel constraint."],zh:["按键截面与结构差异","不同按键截面会影响外观、行程、支撑与成型考虑。参考图用于在形成项目专用截面前比较形状。","提供期望顶面形状、键距、壁厚关系以及高度或行程限制。"],image:"/assets/guide-key-sections.webp",altEn:"Reference sheet showing different silicone key sections",altZh:"不同硅胶按键截面参考图"},
];

export function GuidePage({lang}:{lang:Lang}){
  const z=lang==="zh";
  return <SiteShell lang={lang} path="/design-guides/silicone-rubber-keypad"><Breadcrumbs lang={lang} items={[{label:z?"产品":"Products",href:"/products"},{label:z?"硅胶按键":"Silicone rubber keypad",href:"/silicone-rubber-keypad"},{label:z?"设计指南":"Design guide"}]}/><section className="page-hero"><div className="shell page-hero-grid"><div><Eyebrow>{z?"工程资料":"Engineering reference"}</Eyebrow><h1 className="display-title">{z?"硅胶按键设计指南":"Silicone rubber keypad design guide"}</h1></div><div className="page-hero-note"><p>{z?"本页整理岩泉原站公开技术图与参考内容。所有数值与结构只在原图语境中使用，不作为全部产品保证值。":"This page organizes technical diagrams and reference content published on the original Yan Chuen site. Values and constructions remain contextual references, not universal product guarantees."}</p><Link className="text-link" href={localPath(lang,"/silicone-rubber-keypad")}>{z?"返回硅胶产品页":"Back to silicone product"}<ArrowRight size={15}/></Link></div></div></section><section className="section-compact"><div className="shell guide-shell"><GuideNav lang={lang}/><div><details className="guide-mobile-nav"><summary>{z?"展开章节目录":"Open section contents"}</summary><nav>{sections.map(s=><a key={s.id} href={`#${s.id}`}>{(z?s.zh:s.en)[0]}</a>)}</nav></details>{sections.map((s,i)=>{const [title,body,prepare]=z?s.zh:s.en;return <article id={s.id} className="guide-section" key={s.id}><span className="section-number">{String(i+1).padStart(2,"0")}</span><h2>{title}</h2><p>{body}</p><figure className="guide-figure"><a href={s.image} target="_blank" rel="noreferrer" aria-label={`${z?s.altZh:s.altEn} · ${z?"打开大图":"open larger image"}`}><Image src={s.image} alt={z?s.altZh:s.altEn} width={1600} height={1000}/></a><figcaption>{z?"原站公开参考图；点击打开大图。图中数值只按原图上下文阅读。":"Original public-site reference; open for a larger view. Read any values only in the image's original context."}</figcaption></figure><div className="buyer-note"><strong>{z?"买家应准备什么":"What the buyer should prepare"}</strong><span>{prepare}</span></div><Link className="text-link" href={`${localPath(lang,"/request-a-quote")}?product=silicone-rubber-keypad&topic=${s.id}`}>{z?"分享这部分设计需求":"Share requirements for this topic"}<ArrowRight size={15}/></Link></article>})}</div></div></section><CtaBand lang={lang} product="silicone-rubber-keypad"/></SiteShell>;
}

function GuideNav({lang}:{lang:Lang}){const z=lang==="zh";return <aside className="guide-nav"><h2>{z?"本页章节":"On this page"}</h2><ol>{sections.map(s=><li key={s.id}><a href={`#${s.id}`}>{(z?s.zh:s.en)[0]}</a></li>)}</ol></aside>}
