import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

type GuideItem={id:string;en:[string,string,string];zh:[string,string,string];image:string;altEn:string;altZh:string};
const sections:GuideItem[]=[
  {id:"construction",en:["Basic construction","A silicone keypad typically combines a key surface, web or return geometry, conductive area and mounting relationship. The original diagram is a reference for discussing parts—not a universal section for every design.","Share the intended key layout, available height, mounting surface and any existing section drawing."],zh:["基本結構與部件","矽膠按鍵通常需要同時討論按鍵面、回彈結構、導電區域與安裝關係。原圖用於理解部件，不代表所有設計都採用同一截面。","準備按鍵佈局、可用高度、安裝面及已有截面圖。"],image:"/assets/guide-construction.webp",altEn:"Reference illustration of silicone keypad basic construction",altZh:"矽膠按鍵基本結構參考圖"},
  {id:"conductive-design",en:["Conductive design","The public reference shows several conductive-contact patterns. Contact geometry, resistance targets and circuit interface need to be confirmed against the actual electronics and mechanical stack-up.","Share the PCB contact layout, switching requirement and any target resistance or test method that must be reviewed."],zh:["導電觸點與設計形式","公開參考圖展示多種導電觸點形式。觸點幾何、阻值目標與電路介面需結合實際電子與機械疊層確認。","準備 PCB 觸點佈局、開關需求，以及需要評估的目標阻值或測試方法。"],image:"/assets/guide-conductive.webp",altEn:"Reference patterns for conductive keypad design",altZh:"按鍵導電設計形式參考圖"},
  {id:"special-design",en:["Special design reference","Special constructions may address key shape, light behavior, sealing or assembly constraints. The source illustration is useful for identifying a discussion topic, not for assuming a validated solution.","Mark the constraint on a sketch and explain what the feature must do in the final assembly."],zh:["特殊設計參考","特殊結構可能涉及按鍵形狀、燈光表現、密封或裝配限制。原圖用於識別討論主題，不代表方案已經驗證。","在草圖上標出限制，並說明該結構在最終裝配中的用途。"],image:"/assets/guide-special-design.webp",altEn:"Special silicone keypad construction reference",altZh:"矽膠按鍵特殊結構參考圖"},
  {id:"assembly",en:["Assembly considerations","Keypad behavior depends on the surrounding housing, PCB support, compression and alignment. The assembly reference helps identify interfaces that need dimensions and tolerances.","Provide the housing, PCB and keypad relationship, including fasteners, support points and available compression."],zh:["裝配需要討論的問題","按鍵表現會受到外殼、PCB 支撐、壓合與定位影響。裝配參考圖有助識別需要尺寸與公差的介面。","提供外殼、PCB 與按鍵的關係，包括緊固方式、支撐點及可用壓合空間。"],image:"/assets/guide-assembly.webp",altEn:"Silicone keypad assembly design reference",altZh:"矽膠按鍵裝配設計參考圖"},
  {id:"color-and-marking",en:["Color & marking","Base color and visible legends need separate definition. Printing, engraving and other marking methods have different artwork and process implications.","List base colors, legend colors, viewing conditions and any critical alignment or identification requirement."],zh:["顏色、字樣、雕刻與印刷","基體顏色與可見字樣需分別定義。印刷、雕刻等標示方式對應不同圖稿與工藝條件。","列出基體顏色、字樣顏色、觀看條件，以及關鍵對位或識別要求。"],image:"/assets/guide-color-printing.webp",altEn:"Color and printing reference for silicone keys",altZh:"矽膠按鍵顏色與印刷參考圖"},
  {id:"surface-finishes",en:["Surface finishes","Public samples show several finish approaches, including epoxy-style coatings. The correct finish depends on appearance, feel, legend protection and use conditions.","Describe the desired appearance, touch and what the finish is expected to protect; performance needs project testing."],zh:["表面處理參考","公開樣本展示滴膠等多種表面處理思路。合適工藝取決於外觀、觸感、字樣保護和使用條件。","說明預期外觀、觸感及希望保護的內容；性能需按項目測試。"],image:"/assets/guide-epoxy.webp",altEn:"Epoxy coating reference for a silicone key",altZh:"矽膠按鍵滴膠處理參考圖"},
  {id:"artwork",en:["Artwork preparation","Artwork should define legend content, location, orientation and print relationship. Small features and curved surfaces may need process review before final artwork release.","Provide editable artwork where possible and identify critical size, alignment and color references."],zh:["圖稿與印刷準備","圖稿應說明字樣內容、位置、方向與印刷關係。小尺寸特徵和曲面可能需要在正式放圖前做工藝評估。","儘量提供可編輯圖稿，並標註關鍵尺寸、對位和顏色參考。"],image:"/assets/guide-color-printing.webp",altEn:"Reference diagram for keypad legend and printing artwork",altZh:"按鍵字樣與印刷圖稿參考圖"},
  {id:"special-construction",en:["Special construction","Insert features, light paths and non-standard key sections can create dependencies across tooling, molding and assembly. Treat the original image as a prompt for review.","Explain the purpose of the special feature and share the neighboring parts it must fit or interact with."],zh:["特殊結構示意","嵌件、導光或非標準截面會同時影響模具、成型與裝配。原圖只作為評審提示。","說明特殊結構的目的，並提供相鄰配合或互動零件資料。"],image:"/assets/guide-special-design.webp",altEn:"Reference illustration of special silicone keypad construction",altZh:"矽膠按鍵特殊結構示意圖"},
  {id:"life-test",en:["Life-test reference","A life-test diagram explains how repeated actuation may be evaluated. Values shown in a reference image are not a blanket durability guarantee for every keypad.","State the expected duty cycle, actuation method, environment and any acceptance criteria that require agreement."],zh:["壽命測試參考","壽命測試圖說明可能如何進行重複按壓評估。參考圖中的數值不構成所有按鍵的統一耐久保證。","說明預期工作循環、按壓方式、環境與需確認的驗收標準。"],image:"/assets/guide-life-test.webp",altEn:"Reference illustration for silicone keypad life testing",altZh:"矽膠按鍵壽命測試參考圖"},
  {id:"force-stroke",en:["Reading force & stroke","Force/stroke curves help describe tactile response across travel. The exact curve depends on geometry, material, measurement setup and the surrounding assembly.","Share the preferred feel, target travel if known, comparison sample and the measurement condition you need to match."],zh:["力與行程曲線","力與行程曲線用於描述按壓過程中的觸感響應。實際曲線取決於結構、材料、測量方式與周邊裝配。","準備觸感偏好、已知行程目標、對比樣品及需要匹配的測量條件。"],image:"/assets/guide-force-stroke.webp",altEn:"Reference force and stroke curve for silicone rubber keys",altZh:"矽膠按鍵力與行程曲線參考圖"},
  {id:"tolerance",en:["Tolerance reference","Tolerance needs to be discussed by feature and function. A general table can start the conversation, but critical dimensions require drawing-level agreement and measurement definition.","Identify critical-to-function dimensions, datums, fit relationships and how each dimension will be inspected."],zh:["公差參考","公差應按特徵與功能討論。通用表格可以作為起點，但關鍵尺寸仍需在圖紙層面確認測量定義。","標出關鍵功能尺寸、基準、配合關係以及每個尺寸的檢驗方式。"],image:"/assets/guide-assembly.webp",altEn:"Assembly reference used to discuss critical dimensions and tolerances",altZh:"用於討論關鍵尺寸與公差的裝配參考圖"},
  {id:"key-sections",en:["Key sections","Different key sections change appearance, travel, support and molding considerations. The reference sheet helps compare shapes before a project-specific section is developed.","Provide the preferred top profile, key spacing, wall relationship and any height or travel constraint."],zh:["按鍵截面與結構差異","不同按鍵截面會影響外觀、行程、支撐與成型考慮。參考圖用於在形成項目專用截面前比較形狀。","提供期望頂面形狀、鍵距、壁厚關係以及高度或行程限制。"],image:"/assets/guide-key-sections.webp",altEn:"Reference sheet showing different silicone key sections",altZh:"不同矽膠按鍵截面參考圖"},
];

export function GuidePage({lang}:{lang:Lang}){
  const z=lang==="zh";
  return <SiteShell lang={lang} path="/design-guides/silicone-rubber-keypad"><Breadcrumbs lang={lang} items={[{label:z?"產品":"Products",href:"/products"},{label:z?"矽膠按鍵":"Silicone rubber keypad",href:"/silicone-rubber-keypad"},{label:z?"設計指南":"Design guide"}]}/><section className="page-hero"><div className="shell page-hero-grid"><div><Eyebrow>{z?"工程資料":"Engineering reference"}</Eyebrow><h1 className="display-title">{z?"矽膠按鍵設計指南":"Silicone rubber keypad design guide"}</h1></div><div className="page-hero-note"><p>{z?"本頁整理岩泉原站公開技術圖與參考內容。所有數值與結構只在原圖語境中使用，不作為全部產品保證值。":"This page organizes technical diagrams and reference content published on the original Yan Chuen site. Values and constructions remain contextual references, not universal product guarantees."}</p><Link className="text-link" href={localPath(lang,"/silicone-rubber-keypad")}>{z?"返回矽膠產品頁":"Back to silicone product"}<ArrowRight size={15}/></Link></div></div></section><section className="section-compact"><div className="shell guide-shell"><GuideNav lang={lang}/><div><details className="guide-mobile-nav"><summary>{z?"展開章節目錄":"Open section contents"}</summary><nav>{sections.map(s=><a key={s.id} href={`#${s.id}`}>{(z?s.zh:s.en)[0]}</a>)}</nav></details>{sections.map((s,i)=>{const [title,body,prepare]=z?s.zh:s.en;return <article id={s.id} className="guide-section" key={s.id}><span className="section-number">{String(i+1).padStart(2,"0")}</span><h2>{title}</h2><p>{body}</p><figure className="guide-figure"><a href={s.image} target="_blank" rel="noreferrer" aria-label={`${z?s.altZh:s.altEn} · ${z?"打開大圖":"open larger image"}`}><Image src={s.image} alt={z?s.altZh:s.altEn} width={1600} height={1000}/></a><figcaption>{z?"原站公開參考圖；點擊打開大圖。圖中數值只按原圖上下文閱讀。":"Original public-site reference; open for a larger view. Read any values only in the image's original context."}</figcaption></figure><div className="buyer-note"><strong>{z?"買家應準備什麼":"What the buyer should prepare"}</strong><span>{prepare}</span></div><Link className="text-link" href={`${localPath(lang,"/request-a-quote")}?product=silicone-rubber-keypad&topic=${s.id}`}>{z?"分享這部分設計需求":"Share requirements for this topic"}<ArrowRight size={15}/></Link></article>})}</div></div></section><CtaBand lang={lang} product="silicone-rubber-keypad"/></SiteShell>;
}

function GuideNav({lang}:{lang:Lang}){const z=lang==="zh";return <aside className="guide-nav"><h2>{z?"本頁章節":"On this page"}</h2><ol>{sections.map(s=><li key={s.id}><a href={`#${s.id}`}>{(z?s.zh:s.en)[0]}</a></li>)}</ol></aside>}
