import Image from "next/image";
import Link from "@/components/site-link";
import { ArrowRight } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

export function ProductsPage({lang}:{lang:Lang}){
  const z=lang==="zh";
  const items=[
    {id:"silicone-keypads",name:z?"矽膠按鍵":"Silicone rubber keypads",desc:z?"按項目討論顏色、字樣、導電觸點、雕刻、包膠及表面處理。":"Project-specific colors, legends, conductive contacts, engraving, overmolding and finishes.",img:"/assets/silicone-keypad-black.webp",alt:z?"黑色矽膠按鍵樣品":"Black silicone keypad sample",tags:z?["多色基體","字樣與圖案","導電設計"]:["Multi-color","Legends","Conductive design"],href:localPath(lang,"/silicone-rubber-keypad")},
    {id:"membrane-keypads",name:z?"薄膜按鍵":"Membrane keypads",desc:z?"適合需要圖形覆膜、薄型結構與電路層配合的介面項目。":"For interface projects that combine a graphic overlay, low-profile construction and circuit layers.",img:"/assets/membrane-keypad.webp",alt:z?"薄膜按鍵樣品":"Membrane keypad sample",tags:z?["圖形覆膜","電路結構","裝配討論"]:["Graphic overlay","Circuit construction","Assembly"],href:`${localPath(lang,"/request-a-quote")}?product=membrane-keypad`},
    {id:"rubber-parts",name:z?"橡膠零件":"Rubber parts",desc:z?"可從零件形狀、裝配位置、使用環境和項目階段開始溝通。":"Begin with component geometry, assembly location, operating environment and project stage.",img:"/assets/rubber-components.webp",alt:z?"橡膠零件與密封件樣品":"Rubber components and seals",tags:z?["模壓零件","裝配配合","環境需求"]:["Molded parts","Assembly fit","Environment"],href:`${localPath(lang,"/request-a-quote")}?product=rubber-parts`},
    {id:"keypad-assemblies",name:z?"按鍵套件與組件":"Keypad kits & assemblies",desc:z?"公開產品組合包含按鍵套件、P+R 與組件；具體組合按項目圖紙與裝配要求確認。":"The public range includes keypad kits, P+R and assemblies; exact construction is reviewed per drawing and assembly need.",img:"/assets/keypad-collection-light.webp",alt:z?"多款按鍵與組件樣品":"Collection of keypad and assembly samples",tags:z?["P+R","組件","結構討論"]:["P+R","Assemblies","Construction review"],href:`${localPath(lang,"/request-a-quote")}?product=keypad-assembly`},
    {id:"conductive-connectors",name:z?"彈性導電連接件":"Elastomeric connectors",desc:z?"以尺寸、壓縮裝配與連接需求為起點；性能需結合實際設計確認。":"Start with dimensions, compression assembly and connection requirements; performance is project-specific.",img:"/assets/silicone-keypad-sample.webp",alt:z?"橡膠與導電相關樣品":"Rubber and conductive component samples",tags:z?["連接方式","裝配空間","工程確認"]:["Connection","Assembly space","Engineering review"],href:`${localPath(lang,"/request-a-quote")}?product=elastomeric-connector`},
    {id:"silicone-tubing",name:z?"矽膠管":"Silicone tubing",desc:z?"岩泉公開產品組合中的另一類橡膠製品；建立正式獨立產品頁前，仍需進一步核實現有素材與規格。":"Another rubber-product family in the public range; source material and specifications need review before a dedicated page.",img:"/assets/silicone-tubing.webp",alt:z?"多色矽膠管樣品":"Colorful silicone tubing samples",tags:z?["產品範圍","尺寸待確認","用途待確認"]:["Product range","Dimensions to confirm","Use to confirm"],href:`${localPath(lang,"/request-a-quote")}?product=silicone-tubing`},
  ];
  return <SiteShell lang={lang} path="/products"><Breadcrumbs lang={lang} items={[{label:z?"產品":"Products"}]}/><section className="page-hero"><div className="shell page-hero-grid"><div><Eyebrow>{z?"產品總覽":"Product overview"}</Eyebrow><h1 className="display-title">{z?"從產品類別進入項目討論":"Find the right starting point for your project"}</h1></div><div className="page-hero-note"><p>{z?"這裡展示已核實的產品組合，而不是銷量排名。每一類產品都有可用的詢價入口；首版完整內容重點放在矽膠按鍵。":"This is the verified product range, not a sales ranking. Every category leads somewhere useful; the first release provides the deepest content for silicone rubber keypads."}</p></div></div></section><section className="section-compact section-white"><div className="shell catalog-grid">{items.map(i=><article id={i.id} className="catalog-card" key={i.id}><Image src={i.img} alt={i.alt} width={500} height={500}/><div><Eyebrow>{i.id.replaceAll("-"," ")}</Eyebrow><h2>{i.name}</h2><p>{i.desc}</p><div className="tag-list">{i.tags.map(x=><span key={x}>{x}</span>)}</div><Link className="text-link" href={i.href}>{i.id==="silicone-keypads"?(z?"查看完整產品頁":"Open detailed product page"):(z?"預填此類需求":"Start a request for this category")}<ArrowRight size={15}/></Link></div></article>)}</div></section><CtaBand lang={lang}/></SiteShell>;
}
