import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

export function ProductsPage({lang}:{lang:Lang}){
  const z=lang==="zh";
  const items=[
    {id:"silicone-keypads",name:z?"硅胶按键":"Silicone rubber keypads",desc:z?"按项目讨论颜色、字符、导电触点、雕刻、包胶及表面处理。":"Project-specific colors, legends, conductive contacts, engraving, overmolding and finishes.",img:"/assets/silicone-keypad-black.webp",alt:z?"黑色硅胶按键样品":"Black silicone keypad sample",tags:z?["多色基体","字符与图案","导电设计"]:["Multi-color","Legends","Conductive design"],href:localPath(lang,"/silicone-rubber-keypad")},
    {id:"membrane-keypads",name:z?"薄膜按键":"Membrane keypads",desc:z?"面向需要图形覆膜、薄型结构与电路层配合的界面项目。":"For interface projects that combine a graphic overlay, low-profile construction and circuit layers.",img:"/assets/membrane-keypad.webp",alt:z?"薄膜按键样品":"Membrane keypad sample",tags:z?["图形覆膜","电路结构","装配讨论"]:["Graphic overlay","Circuit construction","Assembly"],href:`${localPath(lang,"/request-a-quote")}?product=membrane-keypad`},
    {id:"rubber-parts",name:z?"橡胶零件":"Rubber parts",desc:z?"可从零件形状、装配位置、使用环境和项目阶段开始沟通。":"Begin with component geometry, assembly location, operating environment and project stage.",img:"/assets/rubber-components.webp",alt:z?"橡胶零件与密封件样品":"Rubber components and seals",tags:z?["模压零件","装配配合","环境需求"]:["Molded parts","Assembly fit","Environment"],href:`${localPath(lang,"/request-a-quote")}?product=rubber-parts`},
    {id:"keypad-assemblies",name:z?"按键套件与组件":"Keypad kits & assemblies",desc:z?"公开产品组合包含按键套件、P+R 与组件；具体组合按项目图纸与装配要求确认。":"The public range includes keypad kits, P+R and assemblies; exact construction is reviewed per drawing and assembly need.",img:"/assets/keypad-collection-light.webp",alt:z?"多款按键与组件样品":"Collection of keypad and assembly samples",tags:z?["P+R","组件","结构讨论"]:["P+R","Assemblies","Construction review"],href:`${localPath(lang,"/request-a-quote")}?product=keypad-assembly`},
    {id:"conductive-connectors",name:z?"弹性导电连接件":"Elastomeric connectors",desc:z?"以尺寸、压缩装配与连接需求为起点；性能需结合实际设计确认。":"Start with dimensions, compression assembly and connection requirements; performance is project-specific.",img:"/assets/silicone-keypad-sample.webp",alt:z?"橡胶与导电相关样品":"Rubber and conductive component samples",tags:z?["连接方式","装配空间","工程确认"]:["Connection","Assembly space","Engineering review"],href:`${localPath(lang,"/request-a-quote")}?product=elastomeric-connector`},
    {id:"silicone-tubing",name:z?"硅胶管":"Silicone tubing",desc:z?"岩泉公开产品组合中的另一类橡胶制品；正式独立产品页前需进一步核查现有素材与规格。":"Another rubber-product family in the public range; source material and specifications need review before a dedicated page.",img:"/assets/silicone-tubing.webp",alt:z?"多色硅胶管样品":"Colorful silicone tubing samples",tags:z?["产品范围","尺寸待确认","用途待确认"]:["Product range","Dimensions to confirm","Use to confirm"],href:`${localPath(lang,"/request-a-quote")}?product=silicone-tubing`},
  ];
  return <SiteShell lang={lang} path="/products"><Breadcrumbs lang={lang} items={[{label:z?"产品":"Products"}]}/><section className="page-hero"><div className="shell page-hero-grid"><div><Eyebrow>{z?"产品总览":"Product overview"}</Eyebrow><h1 className="display-title">{z?"从产品类别进入项目讨论":"Find the right starting point for your project"}</h1></div><div className="page-hero-note"><p>{z?"这里展示已核实的产品组合，而不是销量排名。每一类产品都有可用的询价入口；首版完整内容重点放在硅胶按键。":"This is the verified product range, not a sales ranking. Every category leads somewhere useful; the first release provides the deepest content for silicone rubber keypads."}</p></div></div></section><section className="section-compact section-white"><div className="shell catalog-grid">{items.map(i=><article id={i.id} className="catalog-card" key={i.id}><Image src={i.img} alt={i.alt} width={500} height={500}/><div><Eyebrow>{i.id.replaceAll("-"," ")}</Eyebrow><h2>{i.name}</h2><p>{i.desc}</p><div className="tag-list">{i.tags.map(x=><span key={x}>{x}</span>)}</div><Link className="text-link" href={i.href}>{i.id==="silicone-keypads"?(z?"查看完整产品页":"Open detailed product page"):(z?"预填此类需求":"Start a request for this category")}<ArrowRight size={15}/></Link></div></article>)}</div></section><CtaBand lang={lang}/></SiteShell>;
}
