import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

export function SiliconePage({lang}:{lang:Lang}){
  const z=lang==="zh";
  const options=z?[
    ["顏色與圖案","說明基體顏色、字樣數量與識別要求；最終顏色和圖稿需項目確認。"],["導電觸點","提供電路與觸點需求，討論導電膠粒或其他公開設計形式。"],["激光雕刻","適用於需要雕刻字樣的工藝討論；耐磨等指標不在 Demo 中預設。"],["塑膠／金屬包膠","說明嵌件、定位與裝配用途，結合樣品與圖紙評估。"],["表面處理","可討論 PU、矽膠手感、金屬外觀、滴膠等公開樣本工藝。"],
  ]:[
    ["Color & legends","Share base colors, legend count and recognition needs; final color and artwork are confirmed per project."],["Conductive contacts","Provide circuit and contact needs to discuss carbon pills or other publicly shown formats."],["Laser engraving","A process route for engraved legends; this demo does not preset abrasion or life guarantees."],["Plastic / metal overmolding","Explain insert, location and assembly purpose for review against samples and drawings."],["Surface finishes","Discuss publicly shown PU, silicone-touch, metal-look, epoxy and related finish samples."],
  ];
  const gallery=[
    ["/assets/silicone-keypad-black.webp",z?"多鍵黑色矽膠按鍵工藝樣本":"Black multi-key silicone keypad process sample"],
    ["/assets/silicone-keypad-grey.webp",z?"帶不同顏色字樣的灰色按鍵工藝樣本":"Grey keypad process sample with colored legends"],
    ["/assets/silicone-keypad-sample.webp",z?"組合式矽膠按鍵工藝樣本":"Assembled silicone keypad process sample"],
    ["/assets/silicone-keypad-multicolor.webp",z?"多色矽膠按鍵工藝樣本":"Multi-color silicone keypad process sample"],
  ];
  const prep=z?[["應用","設備類型、操作方式與使用情境"],["結構","尺寸、安裝空間或現有樣品"],["字樣","圖案、顏色與識別需求"],["觸感","偏好、行程或需討論的問題"],["環境","溫度、清潔或材料要求"],["階段","探索、設計中或可報價"]]:[["Application","Device type, operation and use context"],["Construction","Dimensions, available space or an existing sample"],["Legends","Graphics, colors and recognition needs"],["Feel","Preference, travel or points to discuss"],["Environment","Temperature, cleaning or material requirements"],["Stage","Exploring, designing or ready for quotation"]];
  const faqs=z?[
    ["未有圖紙，可以提出需求嗎？","可以。先說明應用、預計結構、字樣、觸感、使用環境和項目階段；有樣品或草圖也可作為溝通起點。"],["價格、MOQ 和交期是多少？","這些內容取決於項目結構、工藝、數量與評估結果。本 Demo 不虛構通用數字，正式項目由岩泉確認。"],["怎樣說明表面處理偏好？","可指出需要討論的外觀、字樣保護、觸感或工藝樣本；具體工藝能力與結果需按樣品及圖紙評估。"],["認證與性能怎樣確認？","請在 RFQ 中列出項目必須符合的認證、材料、環境或測試要求。現行有效證書、主體與範圍均需正式核實。"],
  ]:[
    ["Can I start without a drawing?","Yes. Describe the application, intended construction, legends, feel, environment and project stage. A sample or sketch can also start the conversation."],["What are the price, MOQ and lead time?","They depend on construction, process, quantity and project review. This demo does not invent universal figures; Yan Chuen would confirm them for a live project."],["How should I describe a finish preference?","Point to the appearance, legend protection, feel or process sample you want to discuss. Exact capability and outcome require sample and drawing review."],["How are certifications and performance confirmed?","List required certification, material, environmental or test conditions in the RFQ. Current certificate validity, entity and scope require formal verification."],
  ];
  return <SiteShell lang={lang} path="/silicone-rubber-keypad"><Breadcrumbs lang={lang} items={[{label:z?"產品":"Products",href:"/products"},{label:z?"矽膠按鍵":"Silicone rubber keypad"}]}/><section className="shell product-hero"><div className="product-hero-copy"><Eyebrow>{z?"訂製產品":"Custom product"}</Eyebrow><h1>{z?"訂製矽膠按鍵":"Custom silicone rubber keypads"}</h1><p className="lead">{z?"將顏色、字樣、導電設計、表面處理、裝配與應用要求放進同一次項目討論。":"Bring color, legends, conductive design, finishes, assembly and application requirements into one project discussion."}</p><div className="meta-line"><span>{z?"按項目評估":"Project reviewed"}</span><span>{z?"可先無圖紙":"Drawing optional"}</span><span>{z?"工程資料可用":"Design references available"}</span></div><div className="hero-actions"><Link className="button" href={`${localPath(lang,"/request-a-quote")}?product=silicone-rubber-keypad`}>{z?"提交矽膠按鍵需求":"Request a silicone keypad quote"}<ArrowRight size={16}/></Link><Link className="button button-secondary" href={localPath(lang,"/design-guides/silicone-rubber-keypad")}>{z?"查看設計指南":"Open design guide"}</Link></div></div><div className="product-hero-image"><Image src="/assets/silicone-keypad-black.webp" alt={z?"多鍵黑色矽膠按鍵樣品":"Black multi-key silicone rubber keypad sample"} fill priority sizes="(max-width:980px) 100vw, 55vw"/></div></section>
  <section className="section section-white"><div className="shell"><div className="section-head"><div><Eyebrow>{z?"訂製選項":"Customization options"}</Eyebrow><h2>{z?"每項工藝，都要回到買家的真實需求":"Connect every process choice to a real requirement"}</h2></div><p>{z?"這些選項來自岩泉公開產品說明或樣品；它們不是統一適用於所有設計的性能承諾。":"These options come from Yan Chuen's public product descriptions or samples. They are not blanket performance promises for every design."}</p></div><div className="option-grid">{options.map(([h,p],i)=><article className="option-card" key={h}><span className="index">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="section shell"><div className="section-head"><div><Eyebrow>{z?"工藝樣本":"Process samples"}</Eyebrow><h2>{z?"查看真實樣品，不冒充客戶案例":"Real samples, not invented customer cases"}</h2></div><p>{z?"點擊圖片可打開較大版本。圖注只說明可見工藝與樣本性質，不把單一樣品延伸成全部產品能力。":"Open any image at a larger size. Captions describe visible process samples without extending one sample into a universal capability claim."}</p></div><div className="gallery-grid">{gallery.map(([src,alt])=><figure key={src}><a href={src} target="_blank" rel="noreferrer" aria-label={`${alt} · ${z?"打開大圖":"open larger image"}`}><Image src={src} alt={alt} width={1000} height={1000}/></a><figcaption>{alt}</figcaption></figure>)}</div></section>
  <section className="section-compact section-white"><div className="shell prep-grid"><div className="prep-intro"><Eyebrow>{z?"設計準備":"Design preparation"}</Eyebrow><h2>{z?"未有完整圖紙，也能先把問題說清楚":"You can begin before every drawing is complete"}</h2><p>{z?"先準備能確認的內容，把未知項標出來，工程討論會更有效。":"Share what is known and flag what is not. That is enough to begin a useful engineering discussion."}</p></div><div className="prep-items">{prep.map(([h,p])=><div key={h}><strong>{h}</strong><span>{p}</span></div>)}</div></div></section>
  <section className="section shell"><div className="engineering-feature"><div className="engineering-visual"><Image src="/assets/guide-conductive.webp" alt={z?"矽膠按鍵導電設計形式參考圖":"Reference diagram of silicone keypad conductive design patterns"} width={1340} height={757}/></div><div className="engineering-copy"><Eyebrow>{z?"關聯工程資料":"Related engineering reference"}</Eyebrow><h2>{z?"結構、導電與裝配需要一起看":"Review construction, contacts and assembly together"}</h2><p>{z?"指南將原站技術圖與可讀說明配對，並把所有目錄連結固定到本頁正確章節。":"The guide pairs original technical diagrams with readable explanations and keeps every table-of-contents link on the correct page."}</p><ul className="check-list">{(z?["基本結構與部件","導電觸點形式","裝配、圖稿、力與行程"]:["Basic construction and parts","Conductive-contact formats","Assembly, artwork, force and stroke"]).map(i=><li key={i}><Check size={18}/><span>{i}</span></li>)}</ul><Link className="button" href={localPath(lang,"/design-guides/silicone-rubber-keypad")}>{z?"閱讀完整指南":"Read the complete guide"}<ArrowRight size={16}/></Link></div></div></section>
  <section className="section-compact section-white"><div className="narrow"><div className="section-head" style={{gridTemplateColumns:"1fr"}}><div><Eyebrow>{z?"採購常見問題":"Purchasing FAQ"}</Eyebrow><h2>{z?"先確認項目條件，再給項目答案":"Project answers require project context"}</h2></div></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span aria-hidden="true">＋</span></summary><p>{a}</p></details>)}</div></div></section><CtaBand lang={lang} product="silicone-rubber-keypad"/></SiteShell>;
}
