import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Lang, localPath } from "@/lib/site";
import { Breadcrumbs, CtaBand, Eyebrow, SiteShell } from "@/components/site-shell";

export function SiliconePage({lang}:{lang:Lang}){
  const z=lang==="zh";
  const options=z?[
    ["颜色与图案","说明基体颜色、字符数量与识别要求；最终颜色和图稿需项目确认。"],["导电触点","提供电路与触点需求，讨论导电胶粒或其他公开设计形式。"],["激光雕刻","适用于需要雕刻字符的工艺讨论；耐磨等指标不在 Demo 中预设。"],["塑料 / 金属包胶","说明嵌件、定位与装配用途，结合样品与图纸评估。"],["表面处理","可讨论 PU、硅胶手感、金属外观、滴胶等公开样本工艺。"],
  ]:[
    ["Color & legends","Share base colors, legend count and recognition needs; final color and artwork are confirmed per project."],["Conductive contacts","Provide circuit and contact needs to discuss carbon pills or other publicly shown formats."],["Laser engraving","A process route for engraved legends; this demo does not preset abrasion or life guarantees."],["Plastic / metal overmolding","Explain insert, location and assembly purpose for review against samples and drawings."],["Surface finishes","Discuss publicly shown PU, silicone-touch, metal-look, epoxy and related finish samples."],
  ];
  const gallery=[
    ["/assets/silicone-keypad-black.webp",z?"多键黑色硅胶按键工艺样本":"Black multi-key silicone keypad process sample"],
    ["/assets/silicone-keypad-grey.webp",z?"带不同颜色字符的灰色按键工艺样本":"Grey keypad process sample with colored legends"],
    ["/assets/silicone-keypad-sample.webp",z?"组合式硅胶按键工艺样本":"Assembled silicone keypad process sample"],
    ["/assets/silicone-keypad-multicolor.webp",z?"多色硅胶按键工艺样本":"Multi-color silicone keypad process sample"],
  ];
  const prep=z?[["应用","设备类型、操作方式与使用情境"],["结构","尺寸、安装空间或现有样品"],["字符","图案、颜色与识别需求"],["触感","偏好、行程或需讨论的问题"],["环境","温度、清洁或材料要求"],["阶段","探索、设计中或可报价"]]:[["Application","Device type, operation and use context"],["Construction","Dimensions, available space or an existing sample"],["Legends","Graphics, colors and recognition needs"],["Feel","Preference, travel or points to discuss"],["Environment","Temperature, cleaning or material requirements"],["Stage","Exploring, designing or ready for quotation"]];
  const faqs=z?[
    ["没有图纸，可以提出需求吗？","可以。先说明应用、预计结构、字符、触感、环境和项目阶段；有样品或草图也可作为沟通起点。"],["价格、MOQ 和交期是多少？","这些内容取决于项目结构、工艺、数量与评估结果。本 Demo 不虚构通用数字，正式项目由岩泉确认。"],["怎样说明表面处理偏好？","可指出需要讨论的外观、字符保护、触感或工艺样本；具体工艺能力与结果需按样品及图纸评估。"],["认证与性能怎样确认？","请在 RFQ 中列出项目必须满足的认证、材料、环境或测试要求。当前有效证书、主体与范围需正式核验。"],
  ]:[
    ["Can I start without a drawing?","Yes. Describe the application, intended construction, legends, feel, environment and project stage. A sample or sketch can also start the conversation."],["What are the price, MOQ and lead time?","They depend on construction, process, quantity and project review. This demo does not invent universal figures; Yan Chuen would confirm them for a live project."],["How should I describe a finish preference?","Point to the appearance, legend protection, feel or process sample you want to discuss. Exact capability and outcome require sample and drawing review."],["How are certifications and performance confirmed?","List required certification, material, environmental or test conditions in the RFQ. Current certificate validity, entity and scope require formal verification."],
  ];
  return <SiteShell lang={lang} path="/silicone-rubber-keypad"><Breadcrumbs lang={lang} items={[{label:z?"产品":"Products",href:"/products"},{label:z?"硅胶按键":"Silicone rubber keypad"}]}/><section className="shell product-hero"><div className="product-hero-copy"><Eyebrow>{z?"定制产品":"Custom product"}</Eyebrow><h1>{z?"定制硅胶按键":"Custom silicone rubber keypads"}</h1><p className="lead">{z?"将颜色、字符、导电设计、表面处理、装配与应用要求放进同一次项目讨论。":"Bring color, legends, conductive design, finishes, assembly and application requirements into one project discussion."}</p><div className="meta-line"><span>{z?"按项目评估":"Project reviewed"}</span><span>{z?"可先无图纸":"Drawing optional"}</span><span>{z?"工程资料可用":"Design references available"}</span></div><div className="hero-actions"><Link className="button" href={`${localPath(lang,"/request-a-quote")}?product=silicone-rubber-keypad`}>{z?"提交硅胶按键需求":"Request a silicone keypad quote"}<ArrowRight size={16}/></Link><Link className="button button-secondary" href={localPath(lang,"/design-guides/silicone-rubber-keypad")}>{z?"查看设计指南":"Open design guide"}</Link></div></div><div className="product-hero-image"><Image src="/assets/silicone-keypad-black.webp" alt={z?"多键黑色硅胶按键样品":"Black multi-key silicone rubber keypad sample"} fill priority sizes="(max-width:980px) 100vw, 55vw"/></div></section>
  <section className="section section-white"><div className="shell"><div className="section-head"><div><Eyebrow>{z?"定制选项":"Customization options"}</Eyebrow><h2>{z?"每项工艺，都要回到买家的真实需求":"Connect every process choice to a real requirement"}</h2></div><p>{z?"这些选项来自岩泉公开产品说明或样品；它们不是统一适用于所有设计的性能承诺。":"These options come from Yan Chuen's public product descriptions or samples. They are not blanket performance promises for every design."}</p></div><div className="option-grid">{options.map(([h,p],i)=><article className="option-card" key={h}><span className="index">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="section shell"><div className="section-head"><div><Eyebrow>{z?"工艺样本":"Process samples"}</Eyebrow><h2>{z?"查看真实样品，不冒充客户案例":"Real samples, not invented customer cases"}</h2></div><p>{z?"点击图片可打开较大版本。图注只说明可见工艺与样本性质，不把单一样品延伸成全部产品能力。":"Open any image at a larger size. Captions describe visible process samples without extending one sample into a universal capability claim."}</p></div><div className="gallery-grid">{gallery.map(([src,alt])=><figure key={src}><a href={src} target="_blank" rel="noreferrer" aria-label={`${alt} · ${z?"打开大图":"open larger image"}`}><Image src={src} alt={alt} width={1000} height={1000}/></a><figcaption>{alt}</figcaption></figure>)}</div></section>
  <section className="section-compact section-white"><div className="shell prep-grid"><div className="prep-intro"><Eyebrow>{z?"设计准备":"Design preparation"}</Eyebrow><h2>{z?"没有完整图纸，也能先把问题说清楚":"You can begin before every drawing is complete"}</h2><p>{z?"先准备能确认的内容，把未知项标出来，工程讨论会更有效。":"Share what is known and flag what is not. That is enough to begin a useful engineering discussion."}</p></div><div className="prep-items">{prep.map(([h,p])=><div key={h}><strong>{h}</strong><span>{p}</span></div>)}</div></div></section>
  <section className="section shell"><div className="engineering-feature"><div className="engineering-visual"><Image src="/assets/guide-conductive.webp" alt={z?"硅胶按键导电设计形式参考图":"Reference diagram of silicone keypad conductive design patterns"} width={1340} height={757}/></div><div className="engineering-copy"><Eyebrow>{z?"关联工程资料":"Related engineering reference"}</Eyebrow><h2>{z?"结构、导电与装配需要一起看":"Review construction, contacts and assembly together"}</h2><p>{z?"指南将原站技术图与可读说明配对，并把所有目录链接固定到本页正确章节。":"The guide pairs original technical diagrams with readable explanations and keeps every table-of-contents link on the correct page."}</p><ul className="check-list">{(z?["基本结构与部件","导电触点形式","装配、图稿、力与行程"]:["Basic construction and parts","Conductive-contact formats","Assembly, artwork, force and stroke"]).map(i=><li key={i}><Check size={18}/><span>{i}</span></li>)}</ul><Link className="button" href={localPath(lang,"/design-guides/silicone-rubber-keypad")}>{z?"阅读完整指南":"Read the complete guide"}<ArrowRight size={16}/></Link></div></div></section>
  <section className="section-compact section-white"><div className="narrow"><div className="section-head" style={{gridTemplateColumns:"1fr"}}><div><Eyebrow>{z?"采购常见问题":"Purchasing FAQ"}</Eyebrow><h2>{z?"先确认项目条件，再给项目答案":"Project answers require project context"}</h2></div></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span aria-hidden="true">＋</span></summary><p>{a}</p></details>)}</div></div></section><CtaBand lang={lang} product="silicone-rubber-keypad"/></SiteShell>;
}
