import Link from "next/link";
import { ArrowRight, CircleCheck, Eye } from "lucide-react";
import { Eyebrow, SiteShell } from "@/components/site-shell";
import { metadataFor } from "@/lib/site";

export const metadata={...metadataFor("岩泉官网改版 Demo｜甲方评审方案","原站问题、国际做法、本 Demo 实际实现与正式上线测量建议。","/proposal","zh"),robots:{index:false,follow:false,noarchive:true}};
const comparisons=[
  ["首屏为通用伙伴口号","用明确品类与采购阶段入口说明业务","新首屏定位、产品导航、工程资料与双 CTA 已落地"],
  ["产品以工艺名和样品为主","用说明、图例与应用需求帮助选型","完整硅胶产品页含选项、样品、准备清单、FAQ 与预填 RFQ"],
  ["硅胶指南 11 个章节链接误连薄膜指南","工程资料有清楚目录、正文与关联入口","12 个规范章节 ID 均指向本页，并连接对应项目需求"],
  ["大量中英文 title 与 description 相同","每页每语言围绕实际搜索与采购主题独立表达","五个采购页面已分别配置英文与简体中文 metadata"],
  ["需求表单只有基础联系字段","覆盖不同项目阶段、可选图纸与明确反馈","多行需求、应用、阶段、附件校验、无图纸路径及隔离演示反馈已实现"],
];
export default function Proposal(){return <SiteShell lang="zh" path="/proposal" quietNav><section className="proposal-hero"><div className="shell"><span className="proposal-status"><CircleCheck size={16}/>私人评审 Demo · 全站 noindex</span><h1 className="display-title">把现有制造实力，变成更清楚的采购路径</h1><p className="lead">这不是一份只谈方向的方案。业务资料、产品选型内容、工程资料修正、双语路径与隔离式 RFQ 已经落在当前可运行网站中。</p><div className="hero-actions"><Link className="button button-light" href="/">打开英文采购路径<ArrowRight size={16}/></Link><Link className="button button-secondary" style={{borderColor:"#fff",color:"#fff"}} href="/zh">打开中文采购路径</Link></div></div></section>
<section className="section shell"><div className="section-head"><div><Eyebrow>A / B / C 对照</Eyebrow><h2>从发现问题，到展示已经完成的改动</h2></div><p>原站证据日期为 2026-10-06。国际同行只用作信息组织参考，不复制界面、参数、文案或客户素材，也不宣称其排名与转化表现。</p></div><div className="comparison-list">{comparisons.map((r,i)=><article className="comparison-card" key={r[0]}><div><span>A · 原站问题 {String(i+1).padStart(2,"0")}</span><h3>{r[0]}</h3></div><div><span>B · 国际做法</span><h3>{r[1]}</h3></div><div><span>C · 本 Demo 实现</span><h3>{r[2]}</h3></div></article>)}</div></section>
<section className="section section-white"><div className="shell"><div className="section-head"><div><Eyebrow>SEO 与测量状态</Eyebrow><h2>把“已实现、待上线、未取得”分开写清楚</h2></div><p>Demo 能证明结构、内容与流程已经可用；不能把尚未发生的排名、收录、有效询盘或订单增长写成结果。</p></div><div className="status-grid"><article className="status-card"><h3>本次已实现</h3><ul><li>清楚的 H1 与正文层级</li><li>中英文独立标题与摘要</li><li>产品 ↔ 指南 ↔ RFQ 内部链接</li><li>图片说明、语言切换与移动端布局</li><li>全站预览 noindex</li></ul></article><article className="status-card"><h3>正式上线需配置</h3><ul><li>主域名与 .com.hk 历史入口决定</li><li>301、生产 canonical 与双向 hreflang</li><li>sitemap 与公开索引开关</li><li>真实 RFQ 接收、安全存储与同意</li><li>真实 generate_lead 事件及权限</li></ul></article><article className="status-card"><h3>数据尚未取得</h3><ul><li>真实关键词排名与 Google 收录量</li><li>全域外链质量</li><li>真实用户 LCP / INP / CLS</li><li>会话、有效询盘与成交基线</li><li>正式上线后的业务结果</li></ul></article></div></div></section>
<section className="section shell"><div className="engineering-feature"><div className="engineering-copy"><Eyebrow>30 / 60 / 90 天建议</Eyebrow><h2>先建立可用基线，再按阶段复盘</h2><p>由甲方网站管理员核对既有 GSC、GA4、Wix 搜索机器人报表、Site Speed 与表单历史。权限取得不是 Demo 开工条件，但会影响正式上线后的归因和持续优化。</p><ul className="check-list"><li><Eye size={18}/><span><strong>30 天：</strong>确认抓取、索引、表单接收与首批查询数据</span></li><li><Eye size={18}/><span><strong>60 天：</strong>复盘页面查询、采购路径与内容缺口</span></li><li><Eye size={18}/><span><strong>90 天：</strong>结合有效询盘质量决定内容与技术迭代</span></li></ul></div><div className="trust-card"><Eyebrow>测量边界</Eyebrow><h3>不使用没有来源的增长数字</h3><p>不会展示“预计提升 300%”、虚构搜索排名或“每月损失订单”。所有新 Demo 性能结果必须标明工具版本、环境、次数、中位数与波动范围；不同环境只并列，不伪装成严格同条件提升。</p><Link className="text-link" href="/design-guides/silicone-rubber-keypad">现场检查正确指南目录<ArrowRight size={15}/></Link></div></div></section></SiteShell>}
