import Link from "@/components/site-link";
import { ArrowRight, CircleCheck, Eye } from "lucide-react";
import { Eyebrow, SiteShell } from "@/components/site-shell";
import { metadataFor, siteOrigin } from "@/lib/site";

const proposalMetadata=metadataFor("岩泉官網改版 Demo｜甲方評審方案","原站問題、國際做法、本 Demo 實際實現與正式上線測量建議。","/proposal","zh");
export const metadata={...proposalMetadata,alternates:{canonical:`${siteOrigin}/proposal`,languages:{en:siteOrigin,"zh-Hant":`${siteOrigin}/proposal`}},openGraph:{...proposalMetadata.openGraph,url:`${siteOrigin}/proposal`},robots:{index:false,follow:false,noarchive:true}};
const comparisons=[
  ["首屏為通用夥伴口號","用明確品類與採購階段入口說明業務","新首屏定位、產品導航、工程資料與雙 CTA 已落地"],
  ["產品以工藝名和樣品為主","用說明、圖例與應用需求幫助選型","完整矽膠產品頁含選項、樣品、準備清單、FAQ 與預填 RFQ"],
  ["矽膠指南 11 個章節連結誤連薄膜指南","工程資料有清楚目錄、正文與關聯入口","12 個規範章節 ID 均指向本頁，並連接對應項目需求"],
  ["大量中英文 title 與 description 相同","每頁每語言圍繞實際搜尋與採購主題獨立表達","五個採購頁面已分別配置英文與繁體中文 metadata"],
  ["需求表單只有基礎聯絡欄位","覆蓋不同項目階段、可選圖紙與明確回饋","多行需求、應用、階段、附件驗證、無圖紙路徑及隔離示範回饋已實現"],
];
export default function Proposal(){return <SiteShell lang="zh" path="/" quietNav><section className="proposal-hero"><div className="shell"><span className="proposal-status"><CircleCheck size={16}/>私人評審 Demo · 全站 noindex</span><h1 className="display-title">把現有製造實力，變成更清楚的採購路徑</h1><p className="lead">這不是一份只談方向的方案。業務資料、產品選型內容、工程資料修正、雙語路徑與隔離式 RFQ 已經落實在目前可運作的網站中。</p><div className="hero-actions"><Link className="button button-light" href="/">開啟英文採購路徑<ArrowRight size={16}/></Link><Link className="button button-secondary" style={{borderColor:"#fff",color:"#fff"}} href="/zh">開啟繁體中文採購路徑</Link></div></div></section>
<section className="section shell"><div className="section-head"><div><Eyebrow>A / B / C 對照</Eyebrow><h2>從發現問題，到展示已經完成的改動</h2></div><p>原站證據日期為 2026-10-06。國際同行只用作資訊組織參考，不會複製介面、參數、文案或客戶素材，也不宣稱其排名與轉換表現。</p></div><div className="comparison-list">{comparisons.map((r,i)=><article className="comparison-card" key={r[0]}><div><span>A · 原站問題 {String(i+1).padStart(2,"0")}</span><h3>{r[0]}</h3></div><div><span>B · 國際做法</span><h3>{r[1]}</h3></div><div><span>C · 本 Demo 實現</span><h3>{r[2]}</h3></div></article>)}</div></section>
<section className="section section-white"><div className="shell"><div className="section-head"><div><Eyebrow>SEO 與測量狀態</Eyebrow><h2>把“已實現、待上線、未取得”分開寫清楚</h2></div><p>Demo 能證明結構、內容與流程已經可用；不能把尚未發生的排名、收錄、有效詢盤或訂單增長寫成結果。</p></div><div className="status-grid"><article className="status-card"><h3>本次已實現</h3><ul><li>清楚的 H1 與正文層級</li><li>中英文獨立標題與摘要</li><li>產品 ↔ 指南 ↔ RFQ 內部連結</li><li>圖片說明、語言切換與流動裝置版面</li><li>全站預覽 noindex</li></ul></article><article className="status-card"><h3>正式上線需配置</h3><ul><li>主域名與 .com.hk 歷史入口決定</li><li>301、生產 canonical 與雙向 hreflang</li><li>sitemap 與公開索引開關</li><li>真實 RFQ 接收、安全儲存與同意</li><li>真實 generate_lead 事件及權限</li></ul></article><article className="status-card"><h3>數據尚未取得</h3><ul><li>真實關鍵詞排名與 Google 收錄量</li><li>全域外部連結品質</li><li>真實使用者 LCP / INP / CLS</li><li>會話、有效詢盤與成交基線</li><li>正式上線後的業務結果</li></ul></article></div></div></section>
<section className="section shell"><div className="engineering-feature"><div className="engineering-copy"><Eyebrow>30 / 60 / 90 天建議</Eyebrow><h2>先建立可用基線，再按階段檢視</h2><p>由甲方網站管理員核對既有 GSC、GA4、Wix 搜尋機器人報表、Site Speed 與表單歷史。權限取得不是 Demo 開工條件，但會影響正式上線後的歸因和持續優化。</p><ul className="check-list"><li><Eye size={18}/><span><strong>30 天：</strong>確認抓取、索引、表單接收與首批查詢數據</span></li><li><Eye size={18}/><span><strong>60 天：</strong>檢視頁面查詢、採購路徑與內容缺口</span></li><li><Eye size={18}/><span><strong>90 天：</strong>結合有效詢盤品質決定內容與技術迭代</span></li></ul></div><div className="trust-card"><Eyebrow>測量邊界</Eyebrow><h3>不使用沒有來源的增長數字</h3><p>不會展示“預計提升 300%”、虛構搜尋排名或“每月損失訂單”。所有新 Demo 性能結果必須標明工具版本、環境、次數、中位數與波動範圍；不同環境只並列，不偽裝成嚴格同條件提升。</p><Link className="text-link" href="/design-guides/silicone-rubber-keypad">現場檢查正確指南目錄<ArrowRight size={15}/></Link></div></div></section></SiteShell>}
